### ISSUE TITLE
API for the REPO 

### ISSUE THREAD

**Issue by alphaolomi** [HackEAC/tanzania-locations-db#1]
Hello HackEAC team,

Great work with the TZ location repo, 

I would like to contribute on the API development, some guidance on that

**Comment by maotora** [comment]
Hi, @alphaolomi 

Glad to hear that, Thanks! ✌️
Been thinking of a new repo for the API.
I think a Nodejs stack will be awesome!

**Comment by maotora** [comment]
@alphaolomi were you able to create the database on PostgreSQL with the given instructions from README?

**Comment by alphaolomi** [comment]
> @alphaolomi were you able to create the database on PostgreSQL with the given instructions from README?

Actually no, I didn't not success creating the database, am looking forward on creating the database on clean  docker setup

**Comment by maotora** [comment]
If you got stuck, I would like to know where so I can clear it up a bit in the README

also, please share your progress with the docker setup.

**Comment by maotora** [comment]
@alphaolomi Yooo, we've got the API made & running!

Made with Nestjs & Prisma [link to the repository.](https://github.com/HackEAC/locations-API)

Feel free to contribute :-)
